# Generated by Django 2.2 on 2021-02-22 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_vaccine_to_be_taken_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('cron_expression', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledReportGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report', to='accounts.Parent')),
                ('scheduled_report', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='relatedscheduledreport', to='accounts.ScheduledReport')),
            ],
        ),
        migrations.CreateModel(
            name='ReportRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('scheduled_report', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reportrecep', to='accounts.ScheduledReport')),
            ],
        ),
    ]
