# Generated by Django 2.2 on 2021-03-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_reportrecipient_scheduledreport_scheduledreportgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledreportgroup',
            name='report',
        ),
        migrations.RemoveField(
            model_name='scheduledreportgroup',
            name='scheduled_report',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='to_be_taken_age_in_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ReportRecipient',
        ),
        migrations.DeleteModel(
            name='ScheduledReport',
        ),
        migrations.DeleteModel(
            name='ScheduledReportGroup',
        ),
    ]
