# Generated by Django 2.2 on 2021-03-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210301_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='vaccine_use',
            field=models.CharField(default='Something', max_length=250, null=True),
        ),
    ]
