# Generated by Django 2.2 on 2021-04-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_vaccine_vaccine_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='next_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
