# Generated by Django 2.2 on 2021-04-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_child_next_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='next_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
