# Generated by Django 2.2 on 2021-04-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210429_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='next_date',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='next_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
